[platformio]
default_envs = lofi-adv

[env:lofi-adv]
platform = espressif32@7.0.1
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -fmerge-all-constants
    -Wl,--wrap=nvs_flash_init
extra_scripts =
    pre:../tools/configure_firmware.py
    post:../tools/check_firmware_size.py
lib_deps =
    https://github.com/m5stack/M5GFX.git#0.2.22
    m5stack/M5Unified@0.2.17
    z3t0/IRremote@4.7.1
    m5stack/M5Cardputer@1.1.1
